sudo: required
language:
  - cpp

script:
  - nvm install v8.7.0
  - npm install -g codecov
  - mkdir build
  - cd build
  - cmake ..
  - npm install
  - npm run js-tests
  - make
  - ./cpp-tests

after_success:
  - npm run coverage
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov