sudo: required
language:
  - cpp

script:
  - nvm install v8.7.0
  - npm install -g codecov
  - npm install -g istanbul
  - mkdir build
  - cd build
  - cmake ..
  - make
  # - npm install
  - npm install -g coveralls
  - npm install -g mocha
  - npm install -g mocha-lcov-reporter
  - npm install -g chai
  - npm install -g nyc
  - npm install -g sinon
  - npm install -g sinon-chai
  - npm run js-tests
  - ./cpp-tests

after_success:
  - npm run coverage
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov